<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="2" tests="3" time="2.661">
 <testsuite name="Login page" timestamp="2019-05-17T11:56:27" hostname="localhost" time="2.661" errors="0" tests="3" skipped="0" disabled="0" failures="2">
  <testcase classname="Login page" name="should have correct titles and button text" time="0.808" />
  <testcase classname="Login page" name="should display an error message to the user if they provided incorrect credentials" time="0.699">
   <failure type="exception" message="Failed: No element found using locator: By(css selector, *[id=&quot;usernam&quot;])"><![CDATA[NoSuchElementError: No element found using locator: By(css selector, *[id="usernam"])
    at elementArrayFinder.getWebElements.then (/Users/i338765/protractor-testing-demo-app/node_modules/protractor/lib/element.ts:851:17)
    at ManagedPromise.invokeCallback_ (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (/Users/i338765/protractor-testing-demo-app/node_modules/protractor/lib/element.ts:482:23)
    at ElementArrayFinder.(anonymous function).args [as sendKeys] (/Users/i338765/protractor-testing-demo-app/node_modules/protractor/lib/element.ts:96:21)
    at ElementFinder.(anonymous function).args [as sendKeys] (/Users/i338765/protractor-testing-demo-app/node_modules/protractor/lib/element.ts:873:14)
    at UserContext.<anonymous> (/Users/i338765/protractor-testing-demo-app/e2e/app.e2e-spec.ts:23:17)
    at /Users/i338765/protractor-testing-demo-app/node_modules/jasminewd2/index.js:112:25
    at new ManagedPromise (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:1067:7)
    at ControlFlow.promise (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2396:12)
    at schedulerExecute (/Users/i338765/protractor-testing-demo-app/node_modules/jasminewd2/index.js:95:18)
    at TaskQueue.execute_ (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2860:25)
    at /Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: Run it("should display an error message to the user if they provided incorrect credentials") in control flow
    at UserContext.<anonymous> (/Users/i338765/protractor-testing-demo-app/node_modules/jasminewd2/index.js:94:19)
    at attempt (/Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4486:26)
    at QueueRunner.run (/Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4402:20)
    at runNext (/Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4446:20)
    at /Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4453:13
    at /Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4356:12
    at /Users/i338765/protractor-testing-demo-app/node_modules/jasminewd2/index.js:64:48
    at ControlFlow.emit (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/events.js:62:21)
    at ControlFlow.shutdown_ (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2565:10)
    at shutdownTask_.MicroTask (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2490:53)
    at MicroTask.asyncRun (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2619:9)
    at /Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From asynchronous test: 
Error
    at Suite.<anonymous> (/Users/i338765/protractor-testing-demo-app/e2e/app.e2e-spec.ts:22:2)
    at addSpecsToSuite (/Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1181:25)
    at Env.describe (/Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1145:7)
    at describe (/Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4593:18)
    at Object.<anonymous> (/Users/i338765/protractor-testing-demo-app/e2e/app.e2e-spec.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (/Users/i338765/protractor-testing-demo-app/node_modules/ts-node/src/index.ts:422:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/i338765/protractor-testing-demo-app/node_modules/ts-node/src/index.ts:425:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/i338765/protractor-testing-demo-app/node_modules/jasmine/lib/jasmine.js:93:5]]>
   </failure>
  </testcase>
  <testcase classname="Login page" name="should redirect the user to the dashboard page if they provided correct credentials" time="1.15">
   <failure type="exception" message="Failed: No element found using locator: By(css selector, *[id=&quot;usernam&quot;])"><![CDATA[NoSuchElementError: No element found using locator: By(css selector, *[id="usernam"])
    at elementArrayFinder.getWebElements.then (/Users/i338765/protractor-testing-demo-app/node_modules/protractor/lib/element.ts:851:17)
    at ManagedPromise.invokeCallback_ (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (/Users/i338765/protractor-testing-demo-app/node_modules/protractor/lib/element.ts:482:23)
    at ElementArrayFinder.(anonymous function).args [as sendKeys] (/Users/i338765/protractor-testing-demo-app/node_modules/protractor/lib/element.ts:96:21)
    at ElementFinder.(anonymous function).args [as sendKeys] (/Users/i338765/protractor-testing-demo-app/node_modules/protractor/lib/element.ts:873:14)
    at UserContext.<anonymous> (/Users/i338765/protractor-testing-demo-app/e2e/app.e2e-spec.ts:33:17)
    at /Users/i338765/protractor-testing-demo-app/node_modules/jasminewd2/index.js:112:25
    at new ManagedPromise (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:1067:7)
    at ControlFlow.promise (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2396:12)
    at schedulerExecute (/Users/i338765/protractor-testing-demo-app/node_modules/jasminewd2/index.js:95:18)
    at TaskQueue.execute_ (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2860:25)
    at /Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: Run it("should redirect the user to the dashboard page if they provided correct credentials") in control flow
    at UserContext.<anonymous> (/Users/i338765/protractor-testing-demo-app/node_modules/jasminewd2/index.js:94:19)
    at attempt (/Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4486:26)
    at QueueRunner.run (/Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4402:20)
    at runNext (/Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4446:20)
    at /Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4453:13
    at /Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4356:12
    at /Users/i338765/protractor-testing-demo-app/node_modules/jasminewd2/index.js:64:48
    at ControlFlow.emit (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/events.js:62:21)
    at ControlFlow.shutdown_ (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2565:10)
    at shutdownTask_.MicroTask (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2490:53)
    at MicroTask.asyncRun (/Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:2619:9)
    at /Users/i338765/protractor-testing-demo-app/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From asynchronous test: 
Error
    at Suite.<anonymous> (/Users/i338765/protractor-testing-demo-app/e2e/app.e2e-spec.ts:31:2)
    at addSpecsToSuite (/Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1181:25)
    at Env.describe (/Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1145:7)
    at describe (/Users/i338765/protractor-testing-demo-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4593:18)
    at Object.<anonymous> (/Users/i338765/protractor-testing-demo-app/e2e/app.e2e-spec.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (/Users/i338765/protractor-testing-demo-app/node_modules/ts-node/src/index.ts:422:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/i338765/protractor-testing-demo-app/node_modules/ts-node/src/index.ts:425:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/i338765/protractor-testing-demo-app/node_modules/jasmine/lib/jasmine.js:93:5]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>